name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CHW0218_README }}
          user: CHW0218
          template: classic
          config_display: large
          config_timezone: America/Toronto
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          config_order: base.header, isocalendar, languages, stars, leetcode
          
          
